### ISSUE TITLE
Refresh button from app widget

### ISSUE THREAD

**Issue by vishaldhaduk4495** [ABausG/home_widget#11]
There is no way to refresh data from widget using  button.

**Comment by leonardocustodio** [comment]
Are you talking about iOS or Android? Do you know an app that can do that? So I can take a look?
PS.: It cannot be a system app because they have "special rights"

**Comment by vishaldhaduk4495** [comment]
I am taking about Android.
For example all whether app where refresh button in widget same like crickbuzz app.
I am justing taking about button support(Click) from widget to app currently only have text support.

**Comment by leonardocustodio** [comment]
Since we are talking about android, this library makes communication from the Flutter app to the Widget by using SharedPreferences, so the only option to have the widget updated besides the background fetching (that you are already doing) is to save everything you want in the sharedpreference and just use a button to "switch" between the info already saved. You can make a button on the widget layout and edit the provider to do that.

I do use the library to display images from the user gallery. So I've just added a image to the layout and I'm saving multiple images at the same time than I just switch between them on the widget.

But if you want to make use of intents (click on the widget's button than send an intent to the app and get the response without opening.... I think you cannot do that with this library right now) But maybe you could use platform code to do that, maybe, not really sure.

**Comment by vishaldhaduk4495** [comment]
#14

**Comment by ABausG** [comment]
Version `0.1.2` contains click listeners.
You can now detect if the App was started via clicking on the HomescreenWidget.
On Android you can also execute Dart Code in the Background. For more Info read the updated README
