### ISSUE TITLE
iOS home widget, is it possible to call dart code with `getTimeline`?

### ISSUE THREAD

**Issue by andrewpmoore** [ABausG/home_widget#118]
As in the title I've got a widget working fine on android and ios. Getting the background updates working on android is easy, but I'm trying to find something reliable on iOS

I was wonder if there's any way within `getTimeline` in the widget be able to call a dart method.
I've got background_fetch package configured, but it's so hit and miss as to whether the call is made. It would seem to make sense if possible to update the widget when it's refreshing the timeline.

**Comment by wwwdata** [comment]
I think this is what @andrewpmoore already knows and is doing. But the question is: How to start a headless Flutter/Dart engine from the widget extension and get fresh data directly from that. Does anybody have a good example for this? Updating data in shared preferences relies on the background job to actually run which might not be the case on iOS. Apple has this `getTimeline` method which might run more often and also depends on whether the user is using the Widget. So that seems to be the better approach to rely on this behavior to fetch new data.

**Comment by GanZhiXiong** [comment]
https://github.com/ABausG/home_widget/issues/202

This should be the same issue as this one, which seems to reload TimeLine only through native Swift

**Comment by ABausG** [comment]
Please check the Interactivity guides how to talk to dart code from the Widgets
