### ISSUE TITLE
Support Uint8List on Android

### ISSUE THREAD

**Issue by ABausG** [ABausG/home_widget#230]
PR #197 adds support for sending `Uint8List` to/from iOS

It would be great to also support this on Android

**Comment by bierbaumtim** [comment]
Unlike iOS SharedPreferences on Android does not support saving arbitrary bytes. There are three ways to handle this.

1. We do not support Uint8List on Android and leave it up to the developers how to encode their data into a compatible format.
2. We add support for Uint8List and encode the data to a base64 String. We also add a prefix like "b64:" so that when the plugin reads the data, it knows that a conversion from base64 to ByteArray is required.
3. Like Option 2 but instead of a prefix, an a additional value is stored that specifies the format of the original value. When getWidgetData is called, it checks wether a format has been specified and decodes the stored data accordingly.

I prefer option 3 because I believe that the correct encoding a ByteArray is an implementation detail of the plugin and should mainly effect the implemenation of the plugin, but not other parts of an app that uses this plugin. Also, reading the value from native implementation of a widget just needs a simple conversion from base64 to ByteArray, which is the standard way to store such values.

But what's your opinion on that?

**Comment by ABausG** [comment]
Hmmm I think both option 2 and 3 would be weird because this means users on Android would have to do some juggling around when accessing their data.

I have on my plate to extract some of the logic from `renderFlutterWidget` to be able to save images/bytes directly as files which I think would benefit for this as well. That way users on android (and iOS) can save Byte Data easily as well.

Thanks for looking into it though!
