### ISSUE TITLE
How to invoke Dart method whenever user adds a widget to their home screen for the first time.

### ISSUE THREAD

**Issue by Ruthvik2011** [ABausG/home_widget#249]
I have developed an Android widget with an interactive button triggering a Dart method upon clicking. Now, I want this Dart method to execute not only when the button is clicked but also when the widget is initially placed on the home screen.

I have implemented a workaround for this by listening for the 'android.appwidget.action.APPWIDGET_ENABLED' intent, which signifies the widget being added to the home screen for the first time.

![Screenshot from 2024-04-15 11-33-11](https://github.com/ABausG/home_widget/assets/77824828/2b6d1723-2e2f-4060-83a0-956ce1975c9f)

Note:
However, this workaround isn't optimal as it involves creating an additional Flutter engine unnecessarily.

**Comment by cafoga98** [comment]
@Ruthvik2011 
I have solved it in the following way, I hope it helps you.

Configure a PendingIntent inside onUpdate method, this found in your AppWidgetProvider, see the [Interactive Widgets section](https://pub.dev/packages/home_widget/versions/0.5.0#interactive-widgets) for example.

```
val backgroundIntent = HomeWidgetBackgroundIntent.getBroadcast(
                 context,
                 Uri.parse("homeWidgetEvent://startWidget")
             )
```

and instead of setting it as setOnClickPendingIntent waiting for the user to click, you call it immediately with send() so that it immediately communicates with your [backgroundCallback method](https://pub.dev/packages/home_widget/versions/0.5.0#interactive-widgets) that you previously configured in Dart, for example:

`backgroundIntent.send()`

I have added an extra validation with a string that is empty when configuring the widget for the first time, the complete code would be:

```
val backgroundIntent = HomeWidgetBackgroundIntent.getBroadcast(
                 context,
                 Uri.parse("homeWidgetEvent://startWidget")
             )

             if(widgetData.getString("month", "--") == "--"){
                 backgroundIntent.send()
             }
```

**Comment by Ruthvik2011** [comment]
It's working, Thanks For the help @cafoga98
