### ISSUE TITLE
How to allow user select value on iOS ?

### ISSUE THREAD

**Issue by sunjianan9900** [ABausG/home_widget#61]
When the user long presses the HomeWidget, the Event selector will be displayed, and then select the corresponding value to display
How should it be achieved?
like this:
![IMG_5095](https://user-images.githubusercontent.com/10936316/147313000-6bb76d13-1d00-48b6-a8d6-9616b60bec6c.jpg)

**Comment by ABausG** [comment]
Please refer to the official iOS documentation for this as this is all native code

https://developer.apple.com/documentation/widgetkit/making-a-configurable-widget

In order to write these values back you can use the same storage method as the widget itself. So on the iOS side of things you use:

```swift
let preferences = UserDefaults.init(suiteName: SwiftHomeWidgetPlugin.groupId)
preferences?.setValue(data, forKey: "HomeWidgetConfiguration")
```

and then on the flutter side

```dart
final data = await HomeWidget.getWidgetData('HomeWidgetConfiguration');
```
